### ISSUE TITLE
 Convert it to gray 将图像进行灰度化 报错

### ISSUE THREAD

**Issue by zhaohaipeng17** [eguid/vlpr4j#7]
code exception in:
`public Vector<Mat> plateLocate(Mat src) {    
// Convert it to gray 将图像进行灰度化
        cvtColor(src_blur, src_gray, CV_RGB2GRAY);}`
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.1.0\modules\imgproc\src\color.cpp, line 8000
Exception in thread "main" java.lang.RuntimeException: C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.1.0\modules\imgproc\src\color.cpp:8000: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor

	at org.bytedeco.javacpp.opencv_imgproc.cvtColor(Native Method)
	at cc.eguid.charsocr.core.PlateLocate.plateLocate(PlateLocate.java:77)
	at cc.eguid.charsocr.core.PlateDetect.plateDetect(PlateDetect.java:26)
	at cc.eguid.charsocr.PlateRecognition.plateRecognise(PlateRecognition.java:43)
	at cc.eguid.charsocr.PlateRecognition.main(PlateRecognition.java:96)
![T8](https://user-images.githubusercontent.com/34082146/58714464-5784ea00-83f7-11e9-9775-97823bc06c68.jpg)
![Uploading T8.jpg…]()

**Comment by zhaohaipeng17** [comment]
图片名称不能是汉字。-_-||
